const businessUnitOptions = selected => businessUnits.slice(1).map(([value,label]) => `<option value="${value}" ${selected === value ? "selected" : ""}>${label}</option>`).join("");

leadModal = function () {
  const selected = state.businessUnit === "uperfun" ? "superfun" : (state.businessUnit || "superfun");
  modal("Add New Lead", `<p class="modal-subtitle">Add this lead to the correct Boombastic company.</p><div class="formgrid"><div class="field full"><label>Company *</label><select name="business_unit" required>${businessUnitOptions(selected)}</select></div><div class="field"><label>Lead Name *</label><input name="name" required minlength="2" placeholder="e.g. Ananya Rao"/></div><div class="field"><label>Phone Number *</label><input name="phone" type="tel" required placeholder="e.g. 98765 43210"/></div><div class="field full"><label>Email Address</label><input name="email" type="email" placeholder="e.g. ananya@example.com"/></div><div class="field"><label>Event Type</label><select name="service"><option>Walk-in</option><option>Birthday Party</option><option>Corporate Event</option><option>Kitty Party</option><option>Wedding</option><option>Private Event</option><option>Other</option></select></div><div class="field"><label>Source</label><select name="source"><option value="manual_adding">Manual Adding</option><option value="website">Website</option><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="meta">Meta</option><option value="referral">Referral</option><option value="event">Event</option><option value="outbound">Outbound</option><option value="other">Other</option></select></div><div class="field"><label>Status</label><select name="status"><option value="new">New</option><option value="contacted">Contacted</option><option value="interested">Interested</option><option value="call_back">Follow-up</option><option value="meeting_done">Meeting Done</option><option value="proposal_sent">Proposal Sent</option><option value="on_hold">On Hold</option><option value="won">Closed / Won</option><option value="not_interested">Not Interested</option><option value="lost">Dead / Lost</option><option value="ringing">Ringing</option></select></div><div class="field"><label>Follow-up Date & Time</label><input name="next_follow_up" type="datetime-local"/></div><div class="field full"><label>Assigned To</label><input name="assigned_to" placeholder="e.g. Rahul Mehta" value="${esc(state.user?.name || "")}"/></div></div>`, async data => { const payload=Object.fromEntries(data); Object.keys(payload).forEach(key => {if(payload[key] === "") delete payload[key]}); await api("/leads/",{method:"POST",body:JSON.stringify(payload)}); say(`Lead added to ${nice(payload.business_unit)}`); leads(); });
};

const baseLeadDetail = leadDetail;
leadDetail = async function (id) {
  await baseLeadDetail(id);
  const lead = state.leads.find(item => item._id === id) || await api("/leads/" + id), management = document.querySelector(".lead-management");
  if (!management) return;
  const field = document.createElement("label"); field.className = "drawer-company-field"; field.innerHTML = `Company<select>${businessUnitOptions(lead.business_unit === "uperfun" ? "superfun" : (lead.business_unit || "superfun"))}</select>`; management.prepend(field);
  field.querySelector("select").onchange = async event => { const value=event.target.value; event.target.disabled=true; try{await api(`/leads/${id}`,{method:"PATCH",body:JSON.stringify({business_unit:value})});lead.business_unit=value;say(`Lead moved to ${nice(value)}`)}catch(error){say(error.message);event.target.value=lead.business_unit === "uperfun" ? "superfun" : (lead.business_unit||"superfun")}finally{event.target.disabled=false} };
};

const baseLeadCard = leadCard;
leadCard = lead => { const unit=lead.business_unit === "uperfun" ? "superfun" : (lead.business_unit || "superfun"); return baseLeadCard(lead).replace('<div class="lead-badges">', `<div class="lead-badges"><span class="company-badge ${unit}">${nice(unit)}</span>`); };
