async function settingsPage() {
  shell(`<div class="settings-loading empty">Loading settings…</div>`);
  const s = await api("/settings/me"), checked = value => value ? "checked" : "";
  const channel = (icon, name, key) => `<article><i>${icon}</i><div><b>${name}</b><small class="${s.channels?.[key] ? "connected" : ""}">● ${s.channels?.[key] ? "Connected" : "Not connected"}</small></div><button type="button" data-channel="${name}">Manage</button></article>`;
  document.querySelector(".settings-loading").outerHTML = `<div class="settings-head"><h1>Settings</h1><p>Manage your CRM preferences and workspace.</p></div><form id="settings-form"><div class="settings-layout">
    <nav class="settings-tabs" aria-label="Settings sections"><button type="button" class="active" data-settings-tab="business">▣ <span>Business Profile</span></button><button type="button" data-settings-tab="leads">♙ <span>Lead Management</span></button><button type="button" data-settings-tab="notifications">♧ <span>Notifications</span></button><button type="button" data-settings-tab="security">⌾ <span>Data & Security</span></button></nav>
    <div class="settings-main">
      <section class="settings-section active" data-settings-panel="business"><h2>Business Profile</h2><p>Business information shown across your CRM.</p><div class="settings-card"><h3>Business Information</h3><div class="business-info"><div class="business-logo"><img src="logo.png?v=4" alt="Boombastic logo"/><small>Workspace logo</small></div><div class="settings-fields"><label>Business Name<input name="business_name" required value="${esc(s.business_name)}"/></label><label>Business Type<select name="business_type">${["Entertainment & Events","Event Management","Hospitality","Other"].map(x => `<option ${s.business_type === x ? "selected" : ""}>${x}</option>`).join("")}</select></label><label>Email<input name="business_email" type="email" value="${esc(s.business_email || "")}"/></label><label>Phone Number<input name="business_phone" type="tel" value="${esc(s.business_phone || "")}"/></label><label>Website<input name="website" placeholder="https://..." value="${esc(s.website || "")}"/></label><label>Address<input name="address" value="${esc(s.address || "")}"/></label><label class="wide">Time Zone<select name="timezone"><option value="Asia/Kolkata" ${s.timezone === "Asia/Kolkata" ? "selected" : ""}>(GMT+05:30) India Standard Time</option><option value="UTC" ${s.timezone === "UTC" ? "selected" : ""}>UTC</option></select></label></div></div></div><div class="settings-card"><h3>Working Hours</h3><div class="hours-grid"><label>Monday – Friday<input name="weekday_start" type="time" value="${esc(s.weekday_start)}"/></label><label>Until<input name="weekday_end" type="time" value="${esc(s.weekday_end)}"/></label><label>Saturday – Sunday<input name="weekend_start" type="time" value="${esc(s.weekend_start)}"/></label><label>Until<input name="weekend_end" type="time" value="${esc(s.weekend_end)}"/></label></div></div></section>
      <section class="settings-section" data-settings-panel="leads"><h2>Lead Management</h2><p>Control ownership, reminders and inactive leads.</p><div class="settings-card settings-fields"><label>Default Lead Owner<input name="default_lead_owner" value="${esc(s.default_lead_owner || "")}"/></label><label>Follow-up Reminder<select name="followup_reminder_minutes">${[[15,"15 minutes before"],[30,"30 minutes before"],[60,"1 hour before"],[1440,"1 day before"]].map(([v,n]) => `<option value="${v}" ${s.followup_reminder_minutes === v ? "selected" : ""}>${n}</option>`).join("")}</select></label><label>Lead Inactivity Rule<select name="inactivity_days">${[3,7,14,30].map(v => `<option value="${v}" ${s.inactivity_days === v ? "selected" : ""}>Mark cold after ${v} days</option>`).join("")}</select></label><label class="switch-row">Automatically assign new leads<input name="auto_assign_leads" type="checkbox" ${checked(s.auto_assign_leads)}/><span></span></label></div></section>
      <section class="settings-section" data-settings-panel="notifications"><h2>Notifications</h2><p>Choose the alerts you want the CRM to show.</p><div class="settings-card toggle-list">${[["notify_new_leads","New lead alerts","Notify when a lead enters the CRM."],["notify_followups","Follow-up reminders","Receive reminders before scheduled follow-ups."],["notify_bookings","Booking reminders","Notify about upcoming scheduled bookings."]].map(([key,title,copy]) => `<label><span><b>${title}</b><small>${copy}</small></span><input name="${key}" type="checkbox" ${checked(s[key])}/><i></i></label>`).join("")}</div></section>
      <section class="settings-section" data-settings-panel="security"><h2>Data & Security</h2><p>Your account and workspace security information.</p><div class="settings-card security-list"><div><b>Signed-in account</b><span>${esc(state.user?.email || "—")}</span></div><div><b>Role</b><span>${nice(state.user?.role || "admin")}</span></div><div><b>Session security</b><span>Authentication is required for every CRM request.</span></div><button type="button" id="settings-signout" class="btn">Sign out of this device</button></div></section>
    </div><aside class="channels-card"><h2>Connected Channels</h2><p>Manage lead sources and communication channels.</p>${channel("∞","Meta Leads","meta_leads")}${channel("◎","Instagram","instagram")}${channel("◉","WhatsApp Business","whatsapp")}${channel("⊕","Website Forms","website_forms")}</aside></div><footer class="settings-save"><button type="button" class="btn" id="settings-cancel">Cancel</button><button class="btn primary" type="submit">▣ &nbsp; Save Changes</button></footer></form>`;
  document.querySelectorAll("[data-settings-tab]").forEach(button => button.onclick = () => { document.querySelectorAll("[data-settings-tab]").forEach(x => x.classList.toggle("active", x === button)); document.querySelectorAll("[data-settings-panel]").forEach(x => x.classList.toggle("active", x.dataset.settingsPanel === button.dataset.settingsTab)); });
  document.querySelectorAll("[data-channel]").forEach(button => button.onclick = () => say(`${button.dataset.channel} is configured from your deployment settings`));
  document.querySelector("#settings-signout").onclick = logout; document.querySelector("#settings-cancel").onclick = settingsPage;
  document.querySelector("#settings-form").onsubmit = async event => { event.preventDefault(); const form=event.currentTarget,data=new FormData(form),save=form.querySelector('[type="submit"]'),payload={business_name:data.get("business_name"),business_type:data.get("business_type"),business_email:data.get("business_email")||null,business_phone:data.get("business_phone")||null,website:data.get("website")||null,address:data.get("address")||null,timezone:data.get("timezone"),default_lead_owner:data.get("default_lead_owner")||null,auto_assign_leads:data.has("auto_assign_leads"),followup_reminder_minutes:Number(data.get("followup_reminder_minutes")),inactivity_days:Number(data.get("inactivity_days")),weekday_start:data.get("weekday_start"),weekday_end:data.get("weekday_end"),weekend_start:data.get("weekend_start"),weekend_end:data.get("weekend_end"),notify_new_leads:data.has("notify_new_leads"),notify_followups:data.has("notify_followups"),notify_bookings:data.has("notify_bookings")}; save.disabled=true; try{await api("/settings/me",{method:"PUT",body:JSON.stringify(payload)});say("Settings saved successfully")}catch(error){say(error.message)}finally{save.disabled=false} };
}
